<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>    
    <ScopedCssEnabled>false</ScopedCssEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.4.0" />
    <PackageReference Include="dpz.core.enumlibrary" Version="1.0.1.4" />
    <PackageReference Include="Markdig" Version="0.44.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.1" />
    <PackageReference Include="MongoDB.Bson" Version="3.5.2" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\js\modules\group-chat\canvas-chat.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\modules\group-chat\index.js" />
    <_ContentIncludedByDefault Remove="Properties\launchSettings.json" />
  </ItemGroup>

</Project>
